private_subnet_name: "${private_subnet_name}"
cluster_name: "${cluster_name}"
karpenter_ec2_capacity_type: "${instance_capacity_type}"
excluded_karpenter_ec2_instance_type: "${excluded_instance_type}"
provisioner_name: "${provisioner_name}"

spec:
  labels:
    eks.amazonaws.com/nodegroup: "Services-ng"
